- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH and HTTP
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - 22
    - 80

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
